# **NUMPY**
Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.



A list in Python is a linear data structure that can hold heterogeneous elements they do not require to be declared and are flexible to shrink and grow. On the other hand, an array is a data structure which can hold homogeneous elements, arrays are implemented in Python using the NumPy library. Arrays require less memory than list.

The similarity between an array and a list is that the elements of both array and a list can be identified by its index value

### **METHODS**:
1. np.array()
2. np.ndarray.ndim()
3. np.array.size()
4. np.array.shape()
5. np.array.datatype()
6. numpy.zeroes()
7. numpy.ones()
8.

In [1]:
import numpy as np

l=[2,3,4,5]
print(l)
print(type(l))
print()
arr=np.array(l)
print(arr)
print(type(arr))

[2, 3, 4, 5]
<class 'list'>

[2 3 4 5]
<class 'numpy.ndarray'>


NB: numpy.ndarray.ndim() function return the number of dimensions of an array.

In [2]:
a=np.array([1,2,3,4])
b=np.array([[1,2,3,4],[5,6,7,8]])
print(a.ndim)
print(b.ndim)

1
2


- Now we have few more functions such as np.array.shape, np.array.size and np.array.dtype

- shape will basically return us the total number of rows and columns of the array in a tuple format (number of rows, number of columns)

- size will tell us the total number of elements or values present in the array

- dtype will tell us the data type of values which the array is containing

In [3]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b.shape)
print(b.size)
print(b.dtype)

(2, 4)
8
int64


- The numpy.zeros() function returns a new array of given shape and type, with zeros. Syntax:

numpy.zeros(shape, dtype = None, order = 'C')

In [4]:
# Python Program illustrating
# numpy.zeros method

import numpy as geek

b = geek.zeros(2, dtype = int)
print("Matrix b : \n", b)

a = geek.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = geek.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
b = geek.ones(2, dtype = int)
print("Matrix b : \n", b)

a = geek.ones([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = geek.ones([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [1 1]

Matrix a : 
 [[1 1]
 [1 1]]

Matrix c : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### **RANDOM, RESHAPE, FLATTEN**

In [9]:
# Random function generate values in the range of 0 to 1
np.random.random((3,3))

array([[0.58407141, 0.96171777, 0.02028723],
       [0.41141938, 0.80249062, 0.84032504],
       [0.45339191, 0.57797014, 0.08075247]])

In [10]:
np.random.random()

0.586679239565423

In [11]:
#To generate values in a particular sequence, us arange function
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(1,10,7) #it will also generate 7 random values in from 1 to 10 and those values will be equidistant from each other

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [15]:
# Reshape Array
a=np.random.random((3,4)) #size: 3*4=12
a.reshape(6,2) # the size of elements of the array shoulf be same: 6*2=12.

array([[0.96628277, 0.44817089],
       [0.17829885, 0.29733838],
       [0.74762294, 0.79626124],
       [0.18475296, 0.49598274],
       [0.00283835, 0.84055063],
       [0.46419861, 0.65721393]])

In [16]:
#Flatten array- converts any dimension array to one-dimensional array
a.flatten()

array([0.96628277, 0.44817089, 0.17829885, 0.29733838, 0.74762294,
       0.79626124, 0.18475296, 0.49598274, 0.00283835, 0.84055063,
       0.46419861, 0.65721393])

#### **ARITHMETIC OPERATIONS ON ARRAY**

In [18]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr+1)
print(arr*5)
print(arr-1)
print(arr/2)
print(arr**2)
print(arr%2)

[2 3 4 5 6 7 8 9]
[ 5 10 15 20 25 30 35 40]
[0 1 2 3 4 5 6 7]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[ 1  4  9 16 25 36 49 64]
[1 0 1 0 1 0 1 0]


####  **MAX & MIN, SUM**

In [20]:
print(arr.max())
print(arr.min())

8
1


In [25]:
arr2 = np.array([ [1,2,3],
                  [4,5,6],
                  [7,8,9]])

# To print the element in the column wise
print(arr2.max(axis=0))
print(arr2.min(axis=0))


[7 8 9]
[1 2 3]


In [26]:
arr2.sum()

45

#### **AITHMETIC OPERATIONS ON MULTIPLE ARRAYS**

In [31]:
# To perform arithmetic opeartions on multiple arrays, the shape of the arrays should be same
x= np.array([[1,2,3],[4,5,6]])
y= np.array([[7,8,9],[10,11,12]])
print(x+y)

[[ 8 10 12]
 [14 16 18]]


In [32]:
print(x*y) # It performs normal multiplication and not the dot product

[[ 7 16 27]
 [40 55 72]]


In [34]:
x.dot(y) # It will give error as For matrix multiplication to be valid,
#the number of columns in the first matrix (x) must equal the number of rows in the second matrix (y).
#Here, x has 3 columns, while y has 2 rows, leading to the shape mismatch and the ValueError.

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [35]:
aw= np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
bw= np.array([[10,11,12],
              [13,14,15],
              [16,17,18]])
aw.dot(bw)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [39]:
#ACESSING ELEMENTS IN A 1-D ARRAY
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0])
print(arr[1])
print(arr[-1])
print(arr[-2])
print(arr[:])
print(arr[:-1])
print(arr[2:])
print(arr[2:5])

1
2
8
7
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7]
[3 4 5 6 7 8]
[3 4 5]


In [44]:
#ACESSING Elements of 2-D Array
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
print (arr[:,:])
#arr[:row, :column]
print(arr[:,:-1])

[[7 3 8 6 4]
 [7 2 9 8 6]
 [5 4 2 3 1]]
[[7 3 8 6]
 [7 2 9 8]
 [5 4 2 3]]


#### **SORTING**

In [41]:
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)
print ("Along first axis : \n", arr1)


# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)
print ("\nAlong first axis : \n", arr2)


a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along first axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [40]:
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
print(np.sort(arr , axis = 0, kind = 'mergesort'))
print()
print(np.sort(arr , axis = 1, kind = 'quicksort'))
print()
print(np.sort(arr , kind = 'heapsort'))

[[5 2 2 3 1]
 [7 3 8 6 4]
 [7 4 9 8 6]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]


#### **MERGING**

In [45]:
# Python program explaining
# vstack() function

import numpy as geek

# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays vertically
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [46]:
# Python program explaining
# hstack() function

import numpy as geek

# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [47]:
# Python program explaining
# numpy.concatenate() function

# importing numpy as geek
import numpy as geek

arr1 = geek.array([[2, 4], [6, 8]])
arr2 = geek.array([[3, 5], [7, 9]])

gfg = geek.concatenate((arr1, arr2), axis = 0)

print (gfg)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [48]:
# Python program explaining
# numpy.vsplit() function

# importing numpy as geek
import numpy as geek

arr = geek.arange(9.0).reshape(3, 3)

gfg = geek.vsplit(arr, 1)

print (gfg)

[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


In [49]:
# Python program explaining
# numpy.hsplit() function

# importing numpy as geek
import numpy as geek

arr = geek.arange(16.0).reshape(4, 4)

gfg = geek.hsplit(arr, 2)

print (gfg)

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


#### **AUTOMATION USING NUMPY**

In [50]:
# Say we have a list containing element 1 to 10. Now we want to print the all the elements which are greater than 5
lst = [1,2,3,4,5,6,7,8,9,10]
for i in lst:
  if (i > 5):
    print(i)

6
7
8
9
10


In [51]:
# Now if we convert the list into an array we can do it simply in a single line.
lst = np.array([1,2,3,4,5,6,7,8,9,10])
print(lst[lst>5]) #in a single line we have done the same thing which we did previously and this time without using the for loop

[ 6  7  8  9 10]
